### ISSUE TITLE
OSError: Unable to open file (bad object header version number)

### ISSUE THREAD

**Issue by xiaoshijiu1999** [perslev/U-Time#26]
**I followed the steps in "READM ME" for training and encountered an error "OSError: Unable to open file (bad object header version number)" when I run the command "ut train --num_GPUs=0 --preprocessed --seed 123".**

Traceback (most recent call last):
  File "/home/luan/miniconda3/envs/u-sleep/bin/ut", line 8, in <module>
    sys.exit(entry_func())
  File "/home/luan/miniconda3/envs/u-sleep/lib/python3.7/site-packages/utime/bin/ut.py", line 71, in entry_func
    mod.entry_func(script_args + help_agrs)
  File "/home/luan/miniconda3/envs/u-sleep/lib/python3.7/site-packages/utime/bin/train.py", line 299, in entry_func
    run(args=args, gpu_mon=gpu_mon)
  File "/home/luan/miniconda3/envs/u-sleep/lib/python3.7/site-packages/utime/bin/train.py", line 209, in run
    args.train_on_val, logger)
  File "/home/luan/miniconda3/envs/u-sleep/lib/python3.7/site-packages/utime/utils/scriptutils/train.py", line 103, in get_h5_train_and_val_datasets
    logger=logger)
  File "/home/luan/miniconda3/envs/u-sleep/lib/python3.7/site-packages/utime/dataset/sleep_study_dataset/single_h5_dataset.py", line 105, in __init__
    self.h5_object = h5py.File(self.h5_path, "r")
  File "/home/luan/miniconda3/envs/u-sleep/lib/python3.7/site-packages/h5py/_hl/files.py", line 445, in __init__
    swmr=swmr)
  File "/home/luan/miniconda3/envs/u-sleep/lib/python3.7/site-packages/h5py/_hl/files.py", line 195, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (bad object header version number)_**

**Comment by perslev** [comment]
Hi,

It seems one of the datafiles is corrupted, could you please try and redownload the dataset?

Cheers

**Comment by xiaoshijiu1999** [comment]
> Hi,
> 
> It seems one of the datafiles is corrupted, could you please try and redownload the dataset?
> 
> Cheers
Thank you for your reply. I have successfully solved the problem

**Comment by wenli4313** [comment]
> > Hi,
> > It seems one of the datafiles is corrupted, could you please try and redownload the dataset?
> > Cheers
> > Thank you for your reply. I have successfully solved the problem

Hi，How did you solve it？
