### ISSUE TITLE
FileNotFoundError：[Errno 2] No such file or directory: '/project/lu/test/u-sleep/data/processed/sedf-sc/logs'

### ISSUE THREAD

**Issue by xiaoshijiu1999** [perslev/U-Time#28]
**When I run the command "ut extract --file_regex 'data/sleep-edf-extended/SC*/*PSG.edf' --out_dir 'data/processed/sedf-sc/' --resample 128 --channels 'EEG Fpz-Cz' 'EEG Pz-Oz' 'EOG horizontal' --rename Fpz-Cz Pz-Oz EOG", I've got an error 'No such file or directory: '/project/lu/test/u-sleep/data/processed/sedf-sc/logs'.  Does this mean I need to manually create this folder myself?**

_Traceback (most recent call last):
  File "/home/lu/.conda/envs/u-sleep/bin/ut", line 8, in <module>
    sys.exit(entry_func())
  File "/home/lu/.conda/envs/u-sleep/lib/python3.7/site-packages/utime/bin/ut.py", line 71, in entry_func
    mod.entry_func(script_args + help_agrs)
  File "/home/lu/.conda/envs/u-sleep/lib/python3.7/site-packages/utime/bin/extract.py", line 186, in entry_func
    run(args)
  File "/home/lu/.conda/envs/u-sleep/lib/python3.7/site-packages/utime/bin/extract.py", line 153, in run
    print_calling_method=False)
  File "/home/lu/.conda/envs/u-sleep/lib/python3.7/site-packages/mpunet/logging/logger.py", line 19, in __init__
    create_folders([self.path])
  File "/home/lu/.conda/envs/u-sleep/lib/python3.7/site-packages/mpunet/utils/utils.py", line 286, in create_folders
    safe_make(f, make_func)
  File "/home/lu/.conda/envs/u-sleep/lib/python3.7/site-packages/mpunet/utils/utils.py", line 272, in safe_make
    make_func(path)
FileNotFoundError: [Errno 2] No such file or directory: '/project/lu/test/u-sleep/data/processed/sedf-sc/logs'_

**Comment by perslev** [comment]
Hi,

Yes it seems I forgot to create that folder in the script, so currently you will have to make it yourself in advance. Will fix the script soon.

Cheers
Mathias
