### ISSUE TITLE
'SingleConvUTime' object has no attribute 'loss_functions'

### ISSUE THREAD

**Issue by perslev** [perslev/U-Time#39]
During the training of the model (in particular during the validation) some users get the following error

```
Traceback (most recent call last):
  File "/home/luigi/PycharmProjects/u-sleep/utime/bin/train.py", line 306, in entry_func
    run(args=args, gpu_mon=gpu_mon)
  File "/home/luigi/PycharmProjects/u-sleep/utime/bin/train.py", line 285, in run
    **hparams["fit"])
  File "/home/luigi/PycharmProjects/u-sleep/utime/train/trainer.py", line 165, in fit
    raise e
  File "/home/luigi/PycharmProjects/u-sleep/utime/train/trainer.py", line 147, in fit
    self._fit(batch_size=batch_size, **fit_kwargs)
  File "/home/luigi/PycharmProjects/u-sleep/utime/train/trainer.py", line 244, in _fit
    verbose=verbose
  File "/home/luigi/anaconda3/envs/u-sleep-v0xx/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/luigi/anaconda3/envs/u-sleep-v0xx/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 876, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/luigi/anaconda3/envs/u-sleep-v0xx/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 365, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/luigi/PycharmProjects/u-sleep/utime/callbacks/callbacks.py", line 206, in on_epoch_end
    TPs, relevant, selected, metrics = self.predict()
  File "/home/luigi/PycharmProjects/u-sleep/utime/callbacks/callbacks.py", line 74, in predict
    metrics = self.model.loss_functions + self.model.metrics
AttributeError: 'SingleConvUTime' object has no attribute 'loss_functions'
python-BaseException
```

**Comment by perslev** [comment]
Fixed in 943f1bf8ca24a042bbdd1969effd82ecc67add0f.
