### ISSUE TITLE
ut train error with demo code

### ISSUE THREAD

**Issue by JBurchert** [perslev/U-Time#54]
Hello Mr Perslev,

thank you for your work on Time Series Segmentation, your papers were very interesting and informative! While trying to reproduce your work and started running into an error when running the training step 'ut train --num_gpus=1 --preprocessed ', here is the traceback:

Traceback (most recent call last):
  File "/home/burchert/anaconda3/envs/u-sleep/bin/ut", line 8, in <module>
    sys.exit(entry_func())
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/utime/bin/ut.py", line 103, in entry_func
    mod.entry_func(script_args + help_agrs)
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/utime/bin/train.py", line 305, in entry_func
    run(args=args)
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/utime/bin/train.py", line 215, in run
    train_datasets, val_datasets = dataset_func(hparams, args.no_val, args.train_on_val, args.datasets)
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/utime/utils/scriptutils/train.py", line 134, in get_h5_train_and_val_datasets
    train = _get_dataset(
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/utime/utils/scriptutils/train.py", line 117, in _get_dataset
    dataset = h5_dataset.get_datasets(
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/psg_utils/dataset/sleep_study_dataset/single_h5_dataset.py", line 121, in get_datasets
    datasets.append(H5Dataset(
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/psg_utils/dataset/sleep_study_dataset/single_h5_dataset.py", line 29, in __init__
    pair = H5SleepStudy(
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/psg_utils/dataset/sleep_study/h5_sleep_study.py", line 36, in __init__
    self.load()  # Sets data visibility
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/psg_utils/dataset/sleep_study/h5_sleep_study.py", line 124, in load
    self._class_to_period_dict = {str(class_int): np.asarray(class_indices) for class_int, class_indices
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/psg_utils/dataset/sleep_study/h5_sleep_study.py", line 124, in <dictcomp>
    self._class_to_period_dict = {str(class_int): np.asarray(class_indices) for class_int, class_indices
ValueError: too many values to unpack (expected 2)

I tried both installing the package locally and globally with the PyPi package however got the same error in both cases. Otherwise, I followed the listed steps provided by you. 

Replacing that line with the following should work if I am not overlooking something:
self._class_to_period_dict = {str(class_int): np.asarray(class_inds) for class_int, class_inds in
                                      zip(self.h5_study_object['class_to_index'].keys(),
                                          self.h5_study_object['class_to_index'].values())}

**Comment by perslev** [comment]
Hi Burchert

Thank you for raising this issue. This is indeed a bug, which is fixed on the `develop` branch, see:
https://github.com/perslev/psg-utils/commit/71147f1da8044bf1c962128b1807c2551a244824

I will merge it into `main` asap.

Cheers
Mathias

**Comment by perslev** [comment]
Version `1.0.9` now depends on `psg_utils>=0.07` which should fix this issue. Please let me know if you still experience this or other issue. Cheers Mathias
