### ISSUE TITLE
Overwrite argument used twice 

### ISSUE THREAD

**Issue by JBurchert** [perslev/U-Time#55]
Hello Mr. Perslev,

the extract_hypno.py file has the --overwrite argument twice most likely due to a merge conflict causing the following error:

Traceback (most recent call last):
  File "/home/burchert/anaconda3/envs/u-sleep/bin/ut", line 8, in <module>
    sys.exit(entry_func())
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/utime/bin/ut.py", line 103, in entry_func
    mod.entry_func(script_args + help_agrs)
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/utime/bin/extract_hypno.py", line 111, in entry_func
    parser = get_argparser()
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/site-packages/utime/bin/extract_hypno.py", line 35, in get_argparser
    parser.add_argument("--overwrite", action="store_true",
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/argparse.py", line 1440, in add_argument
    return self._add_action(action)
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/argparse.py", line 1806, in _add_action
    self._optionals._add_action(action)
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/argparse.py", line 1642, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/argparse.py", line 1454, in _add_action
    self._check_conflict(action)
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/argparse.py", line 1591, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/home/burchert/anaconda3/envs/u-sleep/lib/python3.10/argparse.py", line 1600, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --overwrite: conflicting option string: --overwrite

**Comment by perslev** [comment]
Hello JBurchert

Thanks, good catch! I have removed the duplicate flag in 09a482c26fb1d4cbd7a0c0b5272f89ba2c97e8e9.

Cheers
Mathias
