### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by nengwenpeng** [perslev/U-Time#8]
I encountered such an error when I was running, can you tell me the reason?

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tf2/bin/ut", line 33, in <module>
    sys.exit(load_entry_point('utime', 'console_scripts', 'ut')())
  File "/home/ubuntu/tf2/U-Time/utime/bin/ut.py", line 55, in entry_func
    mod.entry_func(parsed.args)
  File "/home/ubuntu/tf2/U-Time/utime/bin/train.py", line 221, in entry_func
    raise e
  File "/home/ubuntu/tf2/U-Time/utime/bin/train.py", line 218, in entry_func
    run(args=args, gpu_mon=gpu_mon)
  File "/home/ubuntu/tf2/U-Time/utime/bin/train.py", line 192, in run
    **hparams["fit"])
  File "/home/ubuntu/tf2/U-Time/utime/train/trainer.py", line 118, in fit
    raise e
  File "/home/ubuntu/tf2/U-Time/utime/train/trainer.py", line 104, in fit
    self._fit(batch_size=batch_size, **fit_kwargs)
  File "/home/ubuntu/tf2/U-Time/utime/train/trainer.py", line 200, in _fit
    verbose=verbose
  File "/home/ubuntu/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1479, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ubuntu/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 876, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ubuntu/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 365, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/ubuntu/tf2/U-Time/utime/callbacks/callbacks.py", line 194, in on_epoch_end
    TPs, relevant, selected, metrics = self.predict()
  File "/home/ubuntu/tf2/U-Time/utime/callbacks/callbacks.py", line 87, in predict
    assert len(metrics_names)-1 == len(metrics)
AssertionError
2020-07-19 21:34:52.871960: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]

**Comment by sweta-r** [comment]
Did someone solve this?

**Comment by nengwenpeng** [comment]
> 有人解决了吗？

After I tried to use a brand new conda environment, the problem was solved. It may be a problem of relying on the library version. I hope to help you

**Comment by perslev** [comment]
Hi!

This issue is likely linked to the version of tensorflow that you have installed. Would you mind sharing which version you are using?

Thanks
Kind regards
Mathias

**Comment by perslev** [comment]
It should work with at least tensorflow 2.1 and 2.2 by the way.

**Comment by sweta-r** [comment]
Upgrading tensorflow worked. Thank you.

**Comment by perslev** [comment]
You're welcome 👍

**Comment by sweta-r** [comment]
This error pops up again with Tensorflow 2.3.1.

**Comment by sweta-r** [comment]
I'm using tensorflow 2.3 and I get this error.

**Comment by perslev** [comment]
Hi @sweta-r! Would you mind trying to fetch the latest version of the repository and re-install the package with pip? Minor changes have been made to the formatting of the hyperparameter file, so I would also suggest you re-run the `ut init` command to create a new, correctly formatted file.

Let me know if you encounter any issues.

Mathias

**Comment by sweta-r** [comment]
Hi @perslev. Thank you for the quick response. This helped!
