### ISSUE TITLE
ValueError when following readme instructions

### ISSUE THREAD

**Issue by neergaard** [perslev/U-Time#9]
Hi! Great paper and great resource!

We have been wanting to do something like this for ourselves for quite some time, but have never gotten around to it, so cool to see UNets being used to time-series segmentation.

I was trying to follow the instructions in the README.md but I get a ValueError related to the MaxPool operation in the first layer:
```
ut train --num_GPUs=1 --channels 'EEG Fpz-Cz' 'EEG Pz-Oz' 'EOG horizontal' 'EMG submental' --force_GPU 0
2020-09-04 10:56:17.990883: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-09-04 10:56:17.992003: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
--------------------------------------------------------------------------------
>>> Logged by: 'run' in 'train.py'
Args dump: {'num_GPUs': 1, 'force_GPU': '0', 'continue_training': False, 'initialize_from': None, 'log_file_prefix': '', 'overwrite': False, 'just_one': False, 'no_val': False, 'max_train_samples_per_epoch': 500000.0, 'val_samples_per_epoch': 50000.0, 'n_epochs': None, 'channels': ['EEG Fpz-Cz', 'EEG Pz-Oz', 'EOG horizontal', 'EMG submental'], 'final_weights_file_name': 'model_weights.h5', 'train_on_val': False}
--------------------------------------------------------------------------------
>>> Logged by: '__init__' in 'hparams.py'
YAML path:    /home/neergaard/utime/hparams.yaml
--------------------------------------------------------------------------------
>>> Logged by: 'log_version' in 'version_controller.py'
utime version: 0.0.1 (master, f4038e8)
--------------------------------------------------------------------------------
>>> Logged by: 'set_value' in 'hparams.py'
Setting value '0.0.1' (type <class 'str'>) in subdir 'None' with name '__VERSION__'
Setting value 'master' (type <class 'str'>) in subdir 'None' with name '__BRANCH__'
Setting value 'f4038e8' (type <class 'str'>) in subdir 'None' with name '__COMMIT__'
--------------------------------------------------------------------------------
>>> Logged by: 'save_current' in 'hparams.py'
Saving current YAML configuration to file:
 /home/neergaard/utime/hparams.yaml
Setting value '['EEG Fpz-Cz', 'EEG Pz-Oz', 'EOG horizontal', 'EMG submental']' (type <class 'list'>) in subdir 'None' with name 'select_channels'
Saving current YAML configuration to file:
 /home/neergaard/utime/hparams.yaml
--------------------------------------------------------------------------------
>>> Logged by: 'log' in 'sleep_study_dataset.py'
[Dataset: dataset_1/TRAIN] SleepStudyDataset(identifier: dataset_1/TRAIN, N pairs: 90, N loaded: 0)
[Dataset: dataset_1/VAL] SleepStudyDataset(identifier: dataset_1/VAL, N pairs: 32, N loaded: 0)
[Dataset: dataset_1/TRAIN] Setting select channels: ['EEG Fpz-Cz', 'EEG Pz-Oz', 'EOG horizontal', 'EMG submental']
[Dataset: dataset_1/VAL] Setting select channels: ['EEG Fpz-Cz', 'EEG Pz-Oz', 'EOG horizontal', 'EMG submental']
[Dataset: dataset_1/TRAIN] Setting sample rate of 100 Hz
[Dataset: dataset_1/VAL] Setting sample rate of 100 Hz
[Dataset: dataset_1/TRAIN] Setting 'drop_class' strip function with parameters {'class_int': 5}...
[Dataset: dataset_1/VAL] Setting 'drop_class' strip function with parameters {'class_int': 5}...
[Dataset: dataset_1/TRAIN] Setting 'zero_out_noisy_epochs' quality control function with parameters {'max_times_global_iqr': 20}...
[Dataset: dataset_1/VAL] Setting 'zero_out_noisy_epochs' quality control function with parameters {'max_times_global_iqr': 20}...
[Dataset: dataset_1/TRAIN] Setting 'RobustScaler' scaler...
[Dataset: dataset_1/VAL] Setting 'RobustScaler' scaler...
[Dataset: dataset_1/TRAIN] Loading 90/90 SleepStudy objects...
Converting time column to int64...
[WARNING] Quality control for sample 'SC4471F0' affected 1/2739 epochs in channel 3
[WARNING] Quality control for sample 'SC4751E0' affected 80/2680 epochs in channel 2
[WARNING] Quality control for sample 'SC4101E0' affected 2/2719 epochs in channel 1
[WARNING] Quality control for sample 'SC4342F0' affected 6/2790 epochs in channel 1
[WARNING] Quality control for sample 'SC4341F0' affected 15/2750 epochs in channel 1
[WARNING] Quality control for sample 'SC4102E0' affected 3/2857 epochs in channel 1
[WARNING] Quality control for sample 'SC4752E0' affected 30/2470 epochs in channel 1
[WARNING] Quality control for sample 'SC4752E0' affected 25/2470 epochs in channel 2
[WARNING] Quality control for sample 'SC4752E0' affected 2369/2470 epochs in channel 3
[WARNING] Quality control for sample 'SC4512E0' affected 2/2750 epochs in channel 1
[WARNING] Quality control for sample 'SC4511E0' affected 1/2712 epochs in channel 1
[WARNING] Quality control for sample 'SC4571F0' affected 7/2836 epochs in channel 1
[WARNING] Quality control for sample 'SC4572F0' affected 60/2873 epochs in channel 1
[WARNING] Quality control for sample 'SC4421E0' affected 6/2764 epochs in channel 3
[WARNING] Quality control for sample 'SC4422E0' affected 3/2682 epochs in channel 3
[WARNING] Quality control for sample 'SC4052E0' affected 6/2804 epochs in channel 3
[WARNING] Quality control for sample 'SC4331F0' affected 1/2809 epochs in channel 1
[WARNING] Quality control for sample 'SC4332F0' affected 2/2758 epochs in channel 1
[WARNING] Quality control for sample 'SC4332F0' affected 11/2758 epochs in channel 3
[WARNING] Quality control for sample 'SC4382F0' affected 5/2770 epochs in channel 2
[WARNING] Quality control for sample 'SC4381F0' affected 2/2750 epochs in channel 1
[WARNING] Quality control for sample 'SC4381F0' affected 1/2750 epochs in channel 2
[WARNING] Quality control for sample 'SC4771G0' affected 1/2756 epochs in channel 1
[WARNING] Quality control for sample 'SC4771G0' affected 1/2756 epochs in channel 2
[WARNING] Quality control for sample 'SC4152E0' affected 2844/2859 epochs in channel 3
[WARNING] Quality control for sample 'SC4151E0' affected 2552/2616 epochs in channel 3
[WARNING] Quality control for sample 'SC4761E0' affected 2559/2610 epochs in channel 3
[WARNING] Quality control for sample 'SC4182E0' affected 3/2842 epochs in channel 3
[WARNING] Quality control for sample 'SC4582G0' affected 25/2634 epochs in channel 2
[WARNING] Quality control for sample 'SC4732E0' affected 1/2519 epochs in channel 1
[WARNING] Quality control for sample 'SC4732E0' affected 1/2519 epochs in channel 2
[WARNING] Quality control for sample 'SC4542F0' affected 7/2680 epochs in channel 1
[WARNING] Quality control for sample 'SC4731E0' affected 11/2780 epochs in channel 1
[WARNING] Quality control for sample 'SC4541F0' affected 6/2739 epochs in channel 1
[WARNING] Quality control for sample 'SC4541F0' affected 1/2739 epochs in channel 2
[WARNING] Quality control for sample 'SC4742E0' affected 5/2650 epochs in channel 1
[WARNING] Quality control for sample 'SC4741E0' affected 28/2689 epochs in channel 1
[WARNING] Quality control for sample 'SC4371F0' affected 39/2850 epochs in channel 2
[WARNING] Quality control for sample 'SC4372F0' affected 120/2840 epochs in channel 2
[WARNING] Quality control for sample 'SC4591G0' affected 14/2819 epochs in channel 2
[WARNING] Quality control for sample 'SC4592G0' affected 21/2040 epochs in channel 1
[WARNING] Quality control for sample 'SC4592G0' affected 28/2040 epochs in channel 2
[WARNING] Quality control for sample 'SC4021E0' affected 2324/2804 epochs in channel 3
[WARNING] Quality control for sample 'SC4601E0' affected 962/2730 epochs in channel 3
[WARNING] Quality control for sample 'SC4602E0' affected 2799/2800 epochs in channel 3
[WARNING] Quality control for sample 'SC4081E0' affected 37/2796 epochs in channel 3
[WARNING] Quality control for sample 'SC4551F0' affected 2624/2772 epochs in channel 3
[WARNING] Quality control for sample 'SC4321E0' affected 18/2689 epochs in channel 1
[WARNING] Quality control for sample 'SC4322E0' affected 30/2616 epochs in channel 1
[WARNING] Quality control for sample 'SC4192E0' affected 6/2605 epochs in channel 2
[WARNING] Quality control for sample 'SC4191E0' affected 6/2774 epochs in channel 2
[WARNING] Quality control for sample 'SC4462F0' affected 1/2854 epochs in channel 2
[WARNING] Quality control for sample 'SC4302E0' affected 171/2808 epochs in channel 3
[WARNING] Quality control for sample 'SC4522E0' affected 2/2774 epochs in channel 1
[WARNING] Quality control for sample 'SC4522E0' affected 18/2774 epochs in channel 3
[WARNING] Quality control for sample 'SC4221E0' affected 1/2700 epochs in channel 1
[WARNING] Quality control for sample 'SC4222E0' affected 2/2760 epochs in channel 1
[Dataset: dataset_1/VAL] Loading 32/32 SleepStudy objects...
[WARNING] Quality control for sample 'SC4492G0' affected 2104/2135 epochs in channel 3
[WARNING] Quality control for sample 'SC4561F0' affected 7/2702 epochs in channel 1
[WARNING] Quality control for sample 'SC4561F0' affected 1/2702 epochs in channel 2
[WARNING] Quality control for sample 'SC4351F0' affected 2/2710 epochs in channel 1
[WARNING] Quality control for sample 'SC4351F0' affected 13/2710 epochs in channel 2
[WARNING] Quality control for sample 'SC4562F0' affected 14/2800 epochs in channel 1
[WARNING] Quality control for sample 'SC4562F0' affected 131/2800 epochs in channel 2
[WARNING] Quality control for sample 'SC4352F0' affected 44/2530 epochs in channel 2
[WARNING] Quality control for sample 'SC4611E0' affected 4/2644 epochs in channel 3
[WARNING] Quality control for sample 'SC4612E0' affected 2730/2730 epochs in channel 3
[WARNING] Quality control for sample 'SC4231E0' affected 3/2743 epochs in channel 3
[WARNING] Quality control for sample 'SC4232E0' affected 34/2635 epochs in channel 3
[WARNING] Quality control for sample 'SC4631E0' affected 40/2758 epochs in channel 3
[WARNING] Quality control for sample 'SC4632E0' affected 1/2848 epochs in channel 3
[WARNING] Quality control for sample 'SC4411E0' affected 1/2728 epochs in channel 3
[WARNING] Quality control for sample 'SC4452F0' affected 2514/2670 epochs in channel 3
[WARNING] Quality control for sample 'SC4451F0' affected 37/2790 epochs in channel 3
[WARNING] Quality control for sample 'SC4262F0' affected 17/2720 epochs in channel 1
[WARNING] Quality control for sample 'SC4262F0' affected 4/2720 epochs in channel 2
[WARNING] Quality control for sample 'SC4261F0' affected 4/2800 epochs in channel 2
[WARNING] Quality control for sample 'SC4122E0' affected 3/2606 epochs in channel 1
[WARNING] Quality control for sample 'SC4111E0' affected 2588/2641 epochs in channel 3
[WARNING] Quality control for sample 'SC4112E0' affected 2752/2780 epochs in channel 3
--------------------------------------------------------------------------------
>>> Logged by: '_assert_scaled' in 'base_sequence.py'
Mean assertion (5 batches):  0.222
Scale assertion (5 batches): 1.333
--------------------------------------------------------------------------------
>>> Logged by: 'log' in 'balanced_random_batch_sequence.py'
[*] BalancedRandomBatchSequence initialized ():
    Batch shape:     [12, 35, 3000, 4]
    Sample prob.:    [0.2, 0.2, 0.2, 0.2, 0.2]
    N pairs:         90
    Margin:          17
    Batch scaling:   False
    All loaded:      True
    N classes:       5 (AUTO-INFERRED)
--------------------------------------------------------------------------------
>>> Logged by: '_assert_scaled' in 'base_sequence.py'
Mean assertion (5 batches):  0.341
Scale assertion (5 batches): 1.458
--------------------------------------------------------------------------------
>>> Logged by: 'log' in 'balanced_random_batch_sequence.py'
[*] BalancedRandomBatchSequence initialized ():
    Batch shape:     [12, 35, 3000, 4]
    Sample prob.:    [0.2, 0.2, 0.2, 0.2, 0.2]
    N pairs:         32
    Margin:          17
    Batch scaling:   False
    All loaded:      True
    N classes:       5 (AUTO-INFERRED)
--------------------------------------------------------------------------------
>>> Logged by: 'log' in 'multi_sequence.py'
[*] ValidationMultiSequence initialized:
    --- Contains 1 sequences
    --- Sequence IDs: dataset_1
--------------------------------------------------------------------------------
>>> Logged by: 'set_value' in 'hparams.py'
Setting value '5' (type <class 'int'>) in subdir 'build' with name 'n_classes'
Setting value '[12, 35, 3000, 4]' (type <class 'list'>) in subdir 'build' with name 'batch_shape'
--------------------------------------------------------------------------------
>>> Logged by: 'save_current' in 'hparams.py'
Saving current YAML configuration to file:
 /home/neergaard/utime/hparams.yaml
--------------------------------------------------------------------------------
>>> Logged by: 'init_model' in 'model_init.py'
Creating new model of type 'UTime'
2020-09-04 10:58:13.194448: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-09-04 10:58:13.246813: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 10:58:13.247876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:23:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.6325GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2020-09-04 10:58:13.247915: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-04 10:58:13.247952: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-04 10:58:13.273823: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-04 10:58:13.280295: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-04 10:58:13.326542: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-04 10:58:13.333335: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-04 10:58:13.333395: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-04 10:58:13.333592: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 10:58:13.334650: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 10:58:13.335684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-09-04 10:58:13.336491: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-09-04 10:58:13.354508: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3399810000 Hz
2020-09-04 10:58:13.355955: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f7954786b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-04 10:58:13.355978: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-04 10:58:13.458840: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 10:58:13.459582: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f79520e920 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-04 10:58:13.459603: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2020-09-04 10:58:13.460209: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 10:58:13.460933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:23:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.6325GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2020-09-04 10:58:13.460966: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-04 10:58:13.460979: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-04 10:58:13.461003: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-04 10:58:13.461017: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-04 10:58:13.461030: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-04 10:58:13.461043: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-04 10:58:13.461054: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-04 10:58:13.461145: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 10:58:13.461803: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 10:58:13.462386: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-09-04 10:58:13.463021: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-04 10:58:14.024431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-04 10:58:14.024482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-09-04 10:58:14.024494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-09-04 10:58:14.025983: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 10:58:14.026906: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 10:58:14.028269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10008 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:23:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/neergaard/miniconda3/envs/utime/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1619, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 10 from 1 for 'encoder_L0_pool/MaxPool' (op: 'MaxPool') with input shapes: [?,16,1,4].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neergaard/miniconda3/envs/utime/bin/ut", line 33, in <module>
    sys.exit(load_entry_point('utime', 'console_scripts', 'ut')())
  File "/home/neergaard/U-Time/utime/bin/ut.py", line 55, in entry_func
    mod.entry_func(parsed.args)
  File "/home/neergaard/U-Time/utime/bin/train.py", line 209, in entry_func
    raise e
  File "/home/neergaard/U-Time/utime/bin/train.py", line 206, in entry_func
    run(args=args, gpu_mon=gpu_mon)
  File "/home/neergaard/U-Time/utime/bin/train.py", line 167, in run
    org_model = init_model(hparams["build"], logger)
  File "/home/neergaard/U-Time/utime/models/model_init.py", line 34, in init_model
    return models.__dict__[cls_name](logger=logger, **build_hparams)
  File "/home/neergaard/U-Time/utime/models/utime.py", line 124, in __init__
    super().__init__(*self.init_model())
  File "/home/neergaard/U-Time/utime/models/utime.py", line 303, in init_model
    **settings)
  File "/home/neergaard/U-Time/utime/models/utime.py", line 164, in create_encoder
    name=l_name + "_pool")(bn)
  File "/home/neergaard/miniconda3/envs/utime/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 773, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/neergaard/miniconda3/envs/utime/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/pooling.py", line 248, in call
    data_format=conv_utils.convert_data_format(self.data_format, 4))
  File "/home/neergaard/miniconda3/envs/utime/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 3875, in max_pool
    name=name)
  File "/home/neergaard/miniconda3/envs/utime/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 5200, in max_pool
    data_format=data_format, name=name)
  File "/home/neergaard/miniconda3/envs/utime/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/neergaard/miniconda3/envs/utime/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 595, in _create_op_internal
    compute_device)
  File "/home/neergaard/miniconda3/envs/utime/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "/home/neergaard/miniconda3/envs/utime/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1786, in __init__
    control_input_ops)
  File "/home/neergaard/miniconda3/envs/utime/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1622, in _create_c_op
    raise ValueError(str(e))
ValueError: Negative dimension size caused by subtracting 10 from 1 for 'encoder_L0_pool/MaxPool' (op: 'MaxPool') with input shapes: [?,16,1,4].
```

It seems strange to me that the dimensions should look like that, which makes me think something has gone wrong in the data processing or loading? I have followed the instructions except adding more channels and forcing to GPU 0 since the default behavior never selects a GPU that is also used for the display.

**Comment by neergaard** [comment]
Arh. It's been quite a while since I've used either TF or Keras, and I was too quick to post. Turns out my Keras configuration JSON was set to `channels_first`, which prompted the `ValueError`.

Should be working now.
